apiVersion: v1
kind: Secret
type: Opaque
data:
  {{ if .Files.Get .Values.secret.configFile }}
  config.json: {{ .Files.Get .Values.secret.configFile | b64enc }}
  {{ else }}
  {{ fail (printf "You must provide a config file (%s)!" .Values.secret.configFile) }}
  {{ end }}
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
